### PR TITLE
 Speed up current "add_features.py" implementation and include basic v502 weights

### PR DESCRIPTION
**Pull request by AncalagonX**
As currently implemented, one leelaz.exe process is spawned to convert only one chunk before exiting. By adding the --cpu-only flag along with using a smaller 32x4 weights file, start-up time for each individual leelaz.exe process is vastly reduced. This saves an enormous amount of time when running "add_features" on many chunks.

I have also included a working 32x4 weights file with this PR.

### CODE REVIEW

**Comment by alreadydone** [comment]
Does the 8x1 weights files (e.g. http://zero.sjeng.org/networks/d645af975ed5b9d08530d092d484482d9aee014f9498c7afcde8570743f85751.gz) at zero.sjeng.org not work?

**Comment by AncalagonX** [comment]
@alreadydone The added file is a v502 weight for @Ttl's the liberty plane + ladder detection branch. This branch currently only supports loading his v502 weights.

I expect if this branch continues development, that restriction will eventually be lifted so that normal v1 and v2 weights can also be used. I also expect someday the `add_features.py` pipeline will be changed to allow each leelaz.exe process to handle more than one chunk before exiting.

But for now, this PR massively increases the `add_features.py` chunk conversion rate by a whopping 1.5 to 2 times on my Windows workstation.

**Comment by Ttl** [comment]
Looks good, but I don't want to pull that big weight file to the repository. Replacing the 8x1 network in src/tests folder would be fine. It could also be run through the quantization script to save little more space.

**Comment by AncalagonX** [comment]
Whew. That's one hell of a commit history on this PR. I'm not very good at git/github—this was actually practice for me.

Changes made in this PR:

1) Deleted /src/tests/0k.txt  (3500kb)
2) Added quantized /src/tests/32_4_se.txt  (2800kb)  - tested, works
3) --cpu-only flag added and weights directory in `add_features.py` adjusted to reflect new location of 32_4_se.txt

**Comment by Ttl** [comment]
Merged. I renamed the file to "0k.txt" since tests expect that.

**Pull request closed without merging**
